### ISSUE TITLE
Error 1 test

### ISSUE THREAD

**Issue by ghost** [shadow-42/lightningcash-gold#1]
![Screenshot_20191110_121950_com anydesk anydeskandroid](https://user-images.githubusercontent.com/48694173/68543208-7929ca80-03b4-11ea-9779-da55be325918.jpg)

**Comment by cryptozeny** [comment]
`--disable-tests`

**Comment by cryptozeny** [comment]
`--disable-tests`

**Comment by Albtraum66** [comment]
make  - - disable-tests?

**Comment by Albtraum66** [comment]
![Screenshot_20191110_140502_com anydesk anydeskandroid](https://user-images.githubusercontent.com/48694173/68544425-5ce15a00-03c3-11ea-8370-5ef484b838ee.jpg)
 Pls again helb 👌

**Comment by MerlinMagic2018** [comment]
and even more :
```./configure --disable-tests --disable-bench --disable-gui-tests --disable-zmq```

**Comment by MerlinMagic2018** [comment]
I think this issue can be closed @shadow-42

**Comment by shadow-42** [comment]
tests can be disabled but keeping issue open to resolve

**Comment by shadow-42** [comment]
fixed in latest commit on www.github.com/lightningcashgold/
